name: C/C++ CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y cmake build-essential libx11-xcb-dev lua5.4 liblua5.4-dev
      
      - name: Run cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
      
      - name: Build
        run: make -j